name: Cron Test

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"

jobs:
  cron-test:
    runs-on: ubuntu-latest

    steps:
      - name: Print Time
        run: |
          echo "Cron Triggered"
          date
          echo "Event = ${{ github.event_name }}"
